---
title: "`ggplot2`: от базового слоя до публикабельной визуализации"
author:
  - name: "Антон Ангельгардт"
    affiliation: "Psy-Вышка 2021"
date: "22.05.2021"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
    toc_depth: 3
---

> <font size = 2>`ggplot2` --- мощный и популярный пакет для визуализации данных. Однако часто построение графиков ограничивается простыми шаблонами и выбором стандартных тем. На мастер-классе мы разберемся с тонкостями логики построения графика с помощью пакета `ggplot2`, научимся управлять отдельными элементами графика, а также узнаем, как подготовить график к публикации в соответствии с требованиями журнала, не используя сторонние программы. Мастер-класс рассчитан на исследователей, владеющих R на среднем уровне, однако я буду рад видеть всех заинтересованных!</font>



# Что есть `ggplot2`?



# Краткий экскурс в `tidyverse`

## `readr`

### `read_csv()` & `read_csv2()`

### `read_tsv()`

### `read_delim()`


## Pipe

## `dplyr` & `tidyr`

## `stringr`

## `forcats`


# Немного теории


# Философия A Layered Grammar of Graphics

# Данные

# Базовая визуализация





